[versions]
# Kotlin
kotlin-core = "1.7.0"
kotlin-coroutines = "1.6.2"

# Other
kodein = "7.12.0"

gradlePlugins-android = "7.0.3"


[libraries]
# Plugins
gradlePlugins-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradlePlugins-android = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugins-android" }

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }

# Kodein
kodein-core = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }


