name: pr

on:
  pull_request:
    types: [ opened, reopened, edited, reopened, synchronize ]

jobs:
  pr:
    name: pr
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Fetch git tags
        run: git fetch --unshallow && git fetch --tags origin

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        run: >-
          ./gradlew
          -PpIsGoogleServicesEnabled=false
          -PpIsGithubActions=true
          :pr
